<a href="https://colab.research.google.com/github/farhanwew/Transcranial-Doppler-Biomedical-comp/blob/main/Transcranial_Doppler_Biomed%20-%20train%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TCD - UltraSound

## Downlaod Data

In [1]:
import kagglehub
from google.colab import userdata
username = userdata.get('KAGGLE_USERNAME')
key = userdata.get('KAGGLE_KEY')
%env KAGGLE_USERNAME=$username
%env KAGGLE_KEY=$key

env: KAGGLE_USERNAME=farhanwew
env: KAGGLE_KEY=51376389df8a5a095fd393132ef1b88f


In [8]:
#!/bin/bash
!kaggle datasets download farhanwew/tcd-ultrasound-data

Dataset URL: https://www.kaggle.com/datasets/farhanwew/tcd-ultrasound-data
License(s): unknown
404 Client Error: Not Found for url: https://www.kaggle.com/api/v1/datasets/download/farhanwew/tcd-ultrasound-data?raw=false


In [3]:
%%capture
!unzip /content/tcd-ultrasound-data.zip

## Referneces

[1] Dataset : https://ieee-dataport.org/open-access/transcranial-doppler-ultrasound-database-philips-cx50-ultrasound-system

[2] [Adaptive Maximal Blood Flow Velocity Estimation
From Transcranial Doppler Echos
](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9146561)

[3] [A Deep Learning Framework for the Detection of Abnormality
in Cerebral Blood Flow Velocity Using Transcranial
Doppler Ultrasound](https://www.mdpi.com/2075-4418/13/12/2000)

[4][ Deep learning-based middle cerebral artery blood flow abnormality
detection using flow velocity waveform derived from transcranial
Doppler ultrasound ](https://doi.org/10.1016/j.bspc.2023.104882)

## Intro

Transcranial Doppler (TCD) merupakan pemeriksaan dengan alat ultrasound (menggunakan gelombang suara ultrasonik) untuk mengevaluasi aliran pembuluh darah otak. Selama pemeriksaan TCD, gelombang suara dipancarkan menembus tulang kepala. Data yang terekam oleh alat menggambarkan pergerakan sel-sel darah di dalam pembuluh darah otak, sehingga kecepatan dan arah dari aliran darah tersebut dapat diukur.

However, due to the low signal-to-noise ratio
of TCD spectrograms, measuring the maximal flow velocity is challenging.

## Visualize the Doppler spectrograms

Doppler spectrogram adalah visualisasi frekuensi Doppler terhadap waktu. Ini dipakai untuk melihat bagaimana kecepatan aliran darah di pembuluh otak berubah dari waktu ke waktu.(CBVF)

Ketika alat TCD ditembakkan ke arteri di otak, gelombang ultrasound dipantulkan oleh sel darah merah yang bergerak. Perubahan frekuensi pantulan ini disebut Doppler shift.

In [4]:
!git clone https://github.com/farhanwew/Transcranial-Doppler-Biomedical-comp.git

Cloning into 'Transcranial-Doppler-Biomedical-comp'...
remote: Enumerating objects: 102, done.
remote: Counting objects: 100% (102/102), done.
remote: Compressing objects: 100% (85/85), done.
remote: Total 102 (delta 17), reused 97 (delta 14), pack-reused 0 (from 0)
Receiving objects: 100% (102/102), 15.94 MiB | 17.38 MiB/s, done.
Resolving deltas: 100% (17/17), done.


In [5]:
pwd

'/content'

In [6]:
 %cd "/content/Transcranial-Doppler-Biomedical-comp/TCD tracing code/Code PY"

/content/Transcranial-Doppler-Biomedical-comp/TCD tracing code/Code PY


In [7]:
!pwd

/content/Transcranial-Doppler-Biomedical-comp/TCD tracing code/Code PY


In [8]:
# !python process_dataset.py \
#          --healthy_path "/content/Healthy Subjects/Healthy Subjects" \
#          --icu_path "/content/ICU Patients/ICU Patients"

Using Healthy data path: /content/Healthy Subjects/Healthy Subjects
Using ICU data path: /content/ICU Patients/ICU Patients
Searching for data...
Found 16 Healthy recordings.
Found 15 ICU recordings (filtered by _MCA).
Processed segments will be saved to: /content/Transcranial-Doppler-Biomedical-comp/TCD tracing code/Code PY/processed_segments
Processing Healthy_Subjects_Recording_1.txt from /content/Healthy Subjects/Healthy Subjects...
  Saved 35 valid segments to processed_segments/Healthy_Subjects_Recording_1_segments.npz
Processing Healthy_Subjects_Recording_10.txt from /content/Healthy Subjects/Healthy Subjects...
  Saved 132 valid segments to processed_segments/Healthy_Subjects_Recording_10_segments.npz
Processing Healthy_Subjects_Recording_11.txt from /content/Healthy Subjects/Healthy Subjects...
  Saved 43 valid segments to processed_segments/Healthy_Subjects_Recording_11_segments.npz
Processing Healthy_Subjects_Recording_12.txt from /content/Healthy Subjects/Healthy Subjects..

In [10]:
import os

# Define the path to the directory to be zipped
directory_to_zip = "/content/Transcranial-Doppler-Biomedical-comp/TCD tracing code/Code PY/processed_segments"

# Define the output zip file name and path. Place it in the parent directory for easier access.
output_zip_file = "/content/processed_segments.zip"

# Ensure the directory exists before attempting to zip
if os.path.exists(directory_to_zip):
    # Use the zip command. The -r flag is for recursive zipping of directories.
    # The first argument is the name of the zip file, followed by the directory to be zipped.
    !zip -r "{output_zip_file}" "{directory_to_zip}"
    print(f"Successfully zipped '{directory_to_zip}' to '{output_zip_file}'")
else:
    print(f"Error: Directory '{directory_to_zip}' not found.")


  adding: content/Transcranial-Doppler-Biomedical-comp/TCD tracing code/Code PY/processed_segments/ (stored 0%)
  adding: content/Transcranial-Doppler-Biomedical-comp/TCD tracing code/Code PY/processed_segments/ICU_Patients_Recording_20_MCA_segments.npz (deflated 63%)
  adding: content/Transcranial-Doppler-Biomedical-comp/TCD tracing code/Code PY/processed_segments/ICU_Patients_Recording_1_MCA_segments.npz (deflated 64%)
  adding: content/Transcranial-Doppler-Biomedical-comp/TCD tracing code/Code PY/processed_segments/Healthy_Subjects_Recording_15_segments.npz (deflated 64%)
  adding: content/Transcranial-Doppler-Biomedical-comp/TCD tracing code/Code PY/processed_segments/Healthy_Subjects_Recording_8_segments.npz (deflated 64%)
  adding: content/Transcranial-Doppler-Biomedical-comp/TCD tracing code/Code PY/processed_segments/ICU_Patients_Recording_2_MCA_segments.npz (deflated 66%)
  adding: content/Transcranial-Doppler-Biomedical-comp/TCD tracing code/Code PY/processed_segments/ICU_Pat

In [57]:
# !python aggregate_segments.py

Scanning processed_segments for .npz files...
Found 31 files. Aggregating...

--- Aggregation Summary ---
Total Healthy Segments: 1664
Total ICU Segments: 2374
Full dataset saved to: tcd_dataset.npz


In [14]:
!python analyze_and_label_sqi.py --dataset_filepath "/content/tcd_dataset.npz"

/content/Transcranial-Doppler-Biomedical-comp/TCD tracing code/Code PY/analyze_and_label_sqi.py:20: RuntimeWarning: All-NaN slice encountered
  healthy_sqi_seg = np.array([np.nanmedian(arr) if arr.size > 0 else np.nan for arr in healthy_sqi_arrays])
/content/Transcranial-Doppler-Biomedical-comp/TCD tracing code/Code PY/analyze_and_label_sqi.py:21: RuntimeWarning: All-NaN slice encountered
  icu_sqi_seg = np.array([np.nanmedian(arr) if arr.size > 0 else np.nan for arr in icu_sqi_arrays])
Total valid segments for SQI_seg analysis: 4031
SQI_seg distribution (all segments):
  Min: 0.00
  Max: 0.95
  Mean: 0.76
  Median: 0.87
  Std Dev: 0.27
  25th Percentile: 0.81
  75th Percentile: 0.90
SQI_seg distribution histogram saved to sqi_seg_distribution.png
/content/Transcranial-Doppler-Biomedical-comp/TCD tracing code/Code PY/analyze_and_label_sqi.py:66: RuntimeWarning: All-NaN slice encountered
  _healthy_sqi_seg_for_labeling = np.array([np.nanmedian(arr) if arr.size > 0 else np.nan for arr in

In [15]:
!python visualize_quality_samples.py

Found 2492 GOOD segments.
Found 517 BAD segments.
Found 1029 BORDERLINE segments.
Quality samples visualization saved to quality_samples.png


In [17]:
!python train_vae.py

Loading dataset...
Total segments for VAE training: 4038
Normalizing data...
Using device: cuda
Starting training...
Epoch [5/50], Loss: 64.5773
Epoch [10/50], Loss: 48.7311
Epoch [15/50], Loss: 44.2256
Epoch [20/50], Loss: 41.3141
Epoch [25/50], Loss: 39.3525
Epoch [30/50], Loss: 37.5867
Epoch [35/50], Loss: 36.5141
Epoch [40/50], Loss: 35.9375
Epoch [45/50], Loss: 35.3532
Epoch [50/50], Loss: 34.7033
VAE model saved to vae_model.pth
Training loss plot saved.
Computing reconstruction errors...
Reconstruction errors saved to recon_errors.npy
Visualizing sample reconstructions...
Reconstruction visualization saved.


In [18]:
!python train_cyclegan.py

Loading data for CycleGAN...
Domain A (Borderline) size: 1029
Domain B (Good) size: 2492
Using device: cuda
Starting CycleGAN training for 20 epochs...
[Epoch 1/20] [D loss: 0.2347] [G loss: 1.7509]
[Epoch 2/20] [D loss: 0.1928] [G loss: 1.7292]
[Epoch 3/20] [D loss: 0.2410] [G loss: 1.4775]
[Epoch 4/20] [D loss: 0.2191] [G loss: 3.1317]
[Epoch 5/20] [D loss: 0.1895] [G loss: 1.3796]
[Epoch 6/20] [D loss: 0.2088] [G loss: 1.4224]
[Epoch 7/20] [D loss: 0.1944] [G loss: 1.1992]
[Epoch 8/20] [D loss: 0.1746] [G loss: 1.3143]
[Epoch 9/20] [D loss: 0.2189] [G loss: 1.1198]
[Epoch 10/20] [D loss: 0.2053] [G loss: 1.0867]
[Epoch 11/20] [D loss: 0.1653] [G loss: 1.2195]
[Epoch 12/20] [D loss: 0.1683] [G loss: 1.1654]
[Epoch 13/20] [D loss: 0.2203] [G loss: 0.7400]
[Epoch 14/20] [D loss: 0.1444] [G loss: 1.1865]
[Epoch 15/20] [D loss: 0.1888] [G loss: 0.8535]
[Epoch 16/20] [D loss: 0.1993] [G loss: 0.9367]
[Epoch 17/20] [D loss: 0.2119] [G loss: 1.0886]
[Epoch 18/20] [D loss: 0.1715] [G loss: 0

In [19]:
!python train_classifier.py


--- Training Scenario: Baseline (No SQA) ---
Data shape: (4038, 1024)
Results for Baseline (No SQA):
  Accuracy: 0.9418
  AUC: 0.9919
  Sensitivity (ICU Recall): 0.9937
  Specificity (Healthy Recall): 0.8679
  Confusion Matrix:
[[289  44]
 [  3 472]]

--- Training Scenario: Proposed (SQA - Good Only) ---
Data shape: (2492, 1024)
Results for Proposed (SQA - Good Only):
  Accuracy: 0.9579
  AUC: 0.9971
  Sensitivity (ICU Recall): 0.9160
  Specificity (Healthy Recall): 1.0000
  Confusion Matrix:
[[249   0]
 [ 21 229]]

--- Preparing GAN Restored Data ---

--- Training Scenario: Proposed + GAN Restoration ---
Data shape: (3521, 1024)
Results for Proposed + GAN Restoration:
  Accuracy: 0.8284
  AUC: 0.9903
  Sensitivity (ICU Recall): 0.7076
  Specificity (Healthy Recall): 0.9933
  Confusion Matrix:
[[296   2]
 [119 288]]

Summary plot saved to classification_results.png
